Controllers/ContaController.cs
using Microsoft.AspNetCore.Mvc;
using MestreDigital.Data;


namespace MestreDigital.Controllers
{
    public class ContaController : Controller
    {
        private readonly UsuarioDal _usuarioDal;
        private readonly UserTokenDal _userTokenDal;

        public ContaController(UsuarioDal usuarioDal, UserTokenDal userTokenDal)
        {
            _usuarioDal = usuarioDal;
            _userTokenDal =  userTokenDal;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(string email, string senha)  
        {
            var hashedPassword = _usuarioDal.GetHashedPasswordByEmail(email);

            if (senha == hashedPassword)
            {
                int? userId = _usuarioDal.CheckUserCredentials(email, hashedPassword);
                if (userId.HasValue)
                {
                    string token = _userTokenDal.CreateToken(userId.Value); 

                    CookieOptions option = new CookieOptions
                    {
                        Expires = DateTime.Now.AddHours(1),
                        HttpOnly = true,
                        Secure = true
                    };

                    Response.Cookies.Append("UserToken", token, option);

                    return RedirectToAction("Index", "EditConteudo");
                }
            }

            ModelState.AddModelError("", "Tentativa de login inválida.");
            return View();
        }

        public IActionResult Logout()
        {
            if (Request.Cookies["UserToken"] != null)
            {
                string token = Request.Cookies["UserToken"].ToString();
                if (_userTokenDal.ValidateToken(token))
                {
                    int? userId = _usuarioDal.GetUserIdByToken(token);
                    if (userId.HasValue)
                    {
                        _userTokenDal.LogoutUser(userId.Value);
                        Response.Cookies.Delete("UserToken");
                    }
                }
            }

            return RedirectToAction("Index", "Home");
        }



        [HttpGet]
        public IActionResult Cadastro()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Sucesso()
        {
            return View();
        }

    }
}

Views/Conta/Cadastro.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,400;0,500;1,900&display=swap" rel="stylesheet">
    <!--Fim Google Fonts-->
    <!--Boostrap icons-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <!--Fim Boostrap icons-->
    <link rel="stylesheet" href="~/css/login.css">
    <!--<link rel="stylesheet" href="~/css/style.css">-->
    <title>Cadastro - Painel Admin</title>
    <style>
        .button {
            padding: 10px 35px;
            font-size: 18px;
            font-weight: 500;
            background-color: rgba(16, 198, 13, 0.662);
            color: white;
            border: 0;
            border-radius: 30px;
            cursor: pointer;
            transition: .2s;
        }

    </style>
</head>
<body>
    <header>
        <!-- Logo da Barra -->
        <div class="interface">
            <div class="logo">
                <a asp-area="" asp-controller="Home" asp-action="Index"><img src="/img/Logo.png" width="120"></a>
            </div>

            <div class="box-login">
                <div class="box-img">
                    <div class="texto-login"><h2>Cadastre-se</h2></div>
                </div><!-- box-img -->
                <form asp-controller="Conta" asp-action="Cadastro" method="post" class="mb-4">
                    <label>Nome:</label>
                    <input type="text" name="nome" placeholder="Seu Nome:" required>

                    <label>E-mail:</label>
                    <input type="email" name="email" placeholder="Seu E-mail:" required>

                    <label>Senha:</label>
                    <input type="password" name="senha" placeholder="Senha:" required>

                    <label>Confirme a Senha:</label>
                    <input class="mb-4" type="password" name="confirmaSenha" placeholder="Confirme a Senha:" required>

                </form>
             <br/>
                <div class="cadastre-se">
                    <a asp-area="" asp-controller="Conta" asp-action="Sucesso" class="text-center">
                        <button class="button" type="submit">Cadastrar</button>
                    </a>
                </div>
                <div class="cadastre-se">
                    <p>Já tem uma conta?</p>
                    <a asp-area="" asp-controller="EditConteudo" asp-action="Index" class="text-center">
                        <button class="button" type="submit">Login</button>
                    </a>
                </div>
            </div> <!-- box-login -->
        </div>
    </header>
</body>
</html>

Views/Conta/Login.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,400;0,500;1,900&display=swap" rel="stylesheet">
    <!--Fim Google Fonts-->
    <!--Boostrap icons-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <!--Fim Boostrap icons-->
    <link rel="stylesheet" href="~/css/login.css">
    <!--<link rel="stylesheet" href="~/css/style.css">-->
    <title>Painel Admin</title>
</head>
<body>
    <header>
        <!-- Logo da Barra -->
        <div class="interface">
            <div class="logo">
                <a asp-area="" asp-controller="Home" asp-action="Index"><img src="/img/Logo.png" width="120"></a>
            </div>

            <div class="box-login">
                <div class="box-img">
                    <div class="boneco"></div>
                    <div class="texto-login"><h2>Login</h2></div>

                </div><!-- box-img -->
                <form asp-controller="Conta" asp-action="Login" method="post">
                    <label>Usuário</label>
                    <input type="text" name="email" placeholder="Usuário:" required>

                    <label>Senha:</label>
                    <input type="password" name="senha" placeholder="Senha:" required>

                    <a href="#">Esqueceu a Senha?</a>

                    <input type="checkbox" name="lembrar-me">
                    <span>Lembrar-me</span>

                    <input type="submit" value="Login">
                </form>
            </div> <!-- box-login -->
         </div> 
    </header> 


</body>
</html>

Views/Conta/Sucesso.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,400;0,500;1,900&display=swap" rel="stylesheet">
    <!--Fim Google Fonts-->
    <!--Boostrap icons-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <!--Fim Boostrap icons-->
    <link rel="stylesheet" href="~/css/login.css">
    <!--<link rel="stylesheet" href="~/css/style.css">-->
    <title>Cadastro - Painel Admin</title>
    <style>
         .button {
            padding: 10px 35px;
            font-size: 18px;
            font-weight: 500;
            background-color: rgba(16, 198, 13, 0.662);
            color: white;
            border: 0;
            border-radius: 30px;
            cursor: pointer;
            transition: .2s;
        }

    </style>
</head>
<body>
    <header>
        <!-- Logo da Barra -->
        <div class="interface">
            <div class="logo">
                <a asp-area="" asp-controller="Home" asp-action="Index"><img src="/img/Logo.png" width="120"></a>
            </div>

            <div class="box-login text-center">
                <div class="box-img text-center">
                    <div class="texto-login"><h2>Cadastro Realizado com Sucesso!</h2></div>
                </div><!-- box-img -->
                <div class="mensagem-sucesso text-center">
                    <p>Seu cadastro foi realizado com sucesso. Seu perfil está em analise, em até 48 horas te enviaremos um email. 
                        Você já pode fazer o login usando suas credenciais, mas não poderá realizar alterações.</p>
                    <a asp-area="" asp-controller="EditConteudo" asp-action="Index" class="text-center">
                        <button class="button" type="submit">Login</button>
                    </a>
                </div>
            </div> <!-- box-login -->
        </div>
    </header>
</body>
</html>